import { z } from "zod";

export const uuidSchema = z.uuid();

/**
 * Idempotency keys: URL-safe tokens generated by clients.
 * Bounded length and charset to prevent abuse of the uniqueness index.
 */
export const idempotencyKeySchema = z
  .string()
  .min(8)
  .max(128)
  .regex(/^[A-Za-z0-9._:-]+$/, "Idempotency key must be URL-safe");

export const currencySchema = z.enum(["MAD"]);

export const positiveMinorSchema = z
  .number()
  .int()
  .positive()
  .max(Number.MAX_SAFE_INTEGER, "Amount exceeds supported range");

export const nonNegativeMinorSchema = z
  .number()
  .int()
  .nonnegative()
  .max(Number.MAX_SAFE_INTEGER, "Amount exceeds supported range");

export const positiveIntSchema = z.number().int().positive();

export const quantitySchema = z.number().int().min(1).max(1_000_000);

/** ISO-8601 datetime with explicit offset (clients send UTC). */
export const isoDateTimeSchema = z.iso.datetime({ offset: true }).transform((value) => new Date(value));

export const paginationSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().uuid().optional(),
});

export const roleSchema = z.enum(["buyer", "seller", "professional", "ops_admin", "admin"]);
